version: "3.7"
services:
  bolt:
    image: bolt-ai:production
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-production
    environment:
      - NODE_ENV=production
      - PORT=5173
      - VITE_LOG_LEVEL=debug
      - DEFAULT_NUM_CTX=32768
      - RUNNING_IN_DOCKER=true
    command: pnpm run dockerstart
    networks:
      - GysinRede
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bolt.rule=Host(`bolt.gysin.pro`)"
        - "traefik.http.routers.bolt.entrypoints=websecure"
        - "traefik.http.routers.bolt.tls=true"
        - "traefik.http.routers.bolt.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.bolt.loadbalancer.server.port=5173"
        - "traefik.docker.network=GysinRede"

networks:
  GysinRede:
    external: true
    name: GysinRede